
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-operators
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: grafana
resources:
- argo-dashboard.yaml
- dashboard.yaml
- datasource.yaml
- grafana.yaml
- jupyterhub-sli-dashboard.yaml
- jupyterhub-usage-dashboard.yaml
